### ISSUE TITLE
List of strings

### ISSUE THREAD

**Issue by andersonbadari** [mirrajabi/okhttp-json-mock#1]
What about reading an array of something?
I mean, in the example there is a `Observable<ArrayList<String>> getUserNumbers` , but it didnt work. It give me the following error _"Error opening asset api/v1/users/1/phonenumbers.json"_ (ive openned your project and tested in it)
How can this be fixed?
In order to make a "workaroud", I need to create a model object that contains this list, but this didnt feel 'right' to me.
thanks.

**Comment by mirrajabi** [comment]
@blitzk01 Thanks for mentioning this,
it was a bug in the library. the interceptor was looking for a file named `phonenumbers.json` where the asset file name was `phoneNumbers.json`. so I removed the `.toLowerCase()` part and now its all good.
Use version `1.1.1` and this problem will be fixed.
