### ISSUE TITLE
This library has a dependency on Android

### ISSUE THREAD

**Issue by maartenvang** [mirrajabi/okhttp-json-mock#2]
This is not mentioned in the repo description anywhere, but it makes this library unsuitable for non-Android projects and tests, unless you want to use Robolectric.

**Comment by mirrajabi** [comment]
I guess you are correct, But do you have any ideas to improve it? What is the main issue?

**Comment by maartenvang** [comment]
The main issue is that the interceptor constructor has a direct dependency on the Android context. An alternative would be to provide the Interceptor with a FileSource or something similar. Which could have an Android and a non-android implementation.

**Comment by mirrajabi** [comment]
True. I'll see what I can do in my spare time

**Comment by mirrajabi** [comment]
@maartenvang You can start using version `2.0` and please close this issue if the problem is solved.

**Comment by maartenvang** [comment]
That was quick. Nice work! 🍻
